# Generated by Django 6.0 on 2025-12-25 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subreddit name, e.g. r/camping', max_length=255, unique=True)),
                ('url', models.URLField(help_text='Full URL to the subreddit', unique=True)),
                ('members', models.PositiveIntegerField(help_text='Number of subscribers at discovery time')),
                ('track', models.BooleanField(default=False, help_text='Whether this community should be actively scraped')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(help_text="Reddit's unique post ID", max_length=50, unique=True)),
                ('title', models.TextField()),
                ('url', models.URLField()),
                ('upvotes', models.IntegerField(help_text='Upvote count at time of scrape')),
                ('comments', models.IntegerField(help_text='Comment count at time of scrape')),
                ('posted_at', models.DateTimeField(blank=True, help_text='Original post creation time', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='scraper.redditcommunity')),
            ],
        ),
    ]
